version: '3.1'
networks:
  dating:

services:
  dating_db:
    container_name: dating_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: heru
    # ports:
    #  - 3306:3306
    networks: 
      - dating

  dating_adminer:
    container_name: dating_adminer
    image: adminer:latest
    restart: always
    ports:
      - 8087:8080
    networks: 
      - dating
  dating_php:
    user: "1000"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dating_php
    restart: always
    environment: 
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - .:/var/www
      # - ./php/php.ini:/etc/php7/php.ini
    networks:
      - dating
  dating_nginx:
    image: nginx:stable-alpine
    container_name: dating_nginx
    restart: always
    ports:
      - "8082:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dating_php
      - dating_db
    networks:
      - dating
